# Normalize GitHub Action
# Run normalize analysis in your CI/CD pipeline
#
# Usage:
#   - uses: your-org/normalize-action@v1
#     with:
#       directory: '.'
#       pattern: '**/*.py'

name: 'Normalize Analysis'
description: 'Run normalize static analysis on your Python codebase'
author: 'Normalize Contributors'

branding:
  icon: 'code'
  color: 'green'

inputs:
  directory:
    description: 'Directory to analyze'
    required: false
    default: '.'
  pattern:
    description: 'Glob pattern for files'
    required: false
    default: '**/*.py'
  rules-check:
    description: 'Run rules check'
    required: false
    default: 'true'
  metrics:
    description: 'Generate metrics'
    required: false
    default: 'true'
  sarif-output:
    description: 'Generate SARIF output'
    required: false
    default: 'true'
  sarif-file:
    description: 'SARIF output file path'
    required: false
    default: 'normalize-results.sarif'
  upload-sarif:
    description: 'Upload SARIF to GitHub Code Scanning'
    required: false
    default: 'true'
  python-version:
    description: 'Python version to use'
    required: false
    default: '3.11'

outputs:
  violations:
    description: 'Number of rule violations found'
    value: ${{ steps.rules.outputs.violations }}
  files-analyzed:
    description: 'Number of files analyzed'
    value: ${{ steps.metrics.outputs.files }}

runs:
  using: 'composite'
  steps:
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: ${{ inputs.python-version }}

    - name: Install normalize
      shell: bash
      run: pip install normalize

    - name: Run rules check
      id: rules
      if: inputs.rules-check == 'true'
      shell: bash
      run: |
        if [ "${{ inputs.sarif-output }}" == "true" ]; then
          normalize rules "${{ inputs.directory }}" \
            --pattern "${{ inputs.pattern }}" \
            --sarif "${{ inputs.sarif-file }}" \
            --json > rules-result.json 2>&1 || true
        else
          normalize rules "${{ inputs.directory }}" \
            --pattern "${{ inputs.pattern }}" \
            --json > rules-result.json 2>&1 || true
        fi

        # Extract violation count
        if [ -f rules-result.json ]; then
          VIOLATIONS=$(cat rules-result.json | python -c "import json,sys; d=json.load(sys.stdin); print(d.get('total_violations', 0))" 2>/dev/null || echo "0")
          echo "violations=$VIOLATIONS" >> $GITHUB_OUTPUT
        else
          echo "violations=0" >> $GITHUB_OUTPUT
        fi

    - name: Upload SARIF
      if: inputs.upload-sarif == 'true' && inputs.sarif-output == 'true'
      uses: github/codeql-action/upload-sarif@v3
      with:
        sarif_file: ${{ inputs.sarif-file }}
      continue-on-error: true

    - name: Generate metrics
      id: metrics
      if: inputs.metrics == 'true'
      shell: bash
      run: |
        normalize metrics "${{ inputs.directory }}" \
          --pattern "${{ inputs.pattern }}" \
          --json > normalize-metrics.json 2>&1 || true

        # Extract file count
        if [ -f normalize-metrics.json ]; then
          FILES=$(cat normalize-metrics.json | python -c "import json,sys; d=json.load(sys.stdin); print(d.get('total_files', 0))" 2>/dev/null || echo "0")
          echo "files=$FILES" >> $GITHUB_OUTPUT
        else
          echo "files=0" >> $GITHUB_OUTPUT
        fi

    - name: Upload metrics artifact
      if: inputs.metrics == 'true'
      uses: actions/upload-artifact@v4
      with:
        name: normalize-metrics
        path: normalize-metrics.json
      continue-on-error: true
